language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
before_script:
  - export FLASK_APP="run.py"
  - export SECRET_KEY="!@#(#_jjdril^&@efr8599"
  - export FLASK_CONFIG="testing"
  - export DB_HOST="localhost"
  - export DB_NAME="diarydb"
  - export TEST_DB="testdb"
  - export DB_USERNAME="chariss"
  - export DB_PASSWORD="pooler32"
  - export JWT_SECRET_KEY="(#_jjdril^&@e"
  - psql -c 'create database diarydb;' -U postgres
  - psql -c "create user chariss with password 'pooler32' createdb;" -U postgres
  - python challenge3/app/create_database.py
script:
  pytest --ignore=Api --cov=challenge3/app/
after_success:
  - coveralls
  - codeclimate
