language: python
python:
  - "3.6"
cache: pip
service:
  -postgresql
install:
  - psql -c 'create database diarydb;' -U postgres
  - pip install -r requirements.txt
script:
  - pytest --ignore=Api --cov=challenge3
after_success:
  - coveralls
