language: python
python:
  - "3.6"
cache: pip
service:
  -postgresql
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
script:
  pytest --ignore=Api
after_success:
  - coveralls
