language: python
python:
  - "3.4"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
script:
  - python -m pytest --with-coverage --cover-package=app
after_success:
  - coveralls