language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
before_script:
  - psql -c 'create database diarydb;' -U postgres
  - psql -c "create user chariss with password 'pooler32' createdb;" -U postgres
  - python challenge3/app/create_database.py
script:
  pytest --ignore=Api --cov=challenge3/
after_success:
  - coveralls
  - codeclimate
